name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      # Không cần 'path: CV-Digital' ở đây vì repo root là nơi cần làm việc

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
      # Không cần 'working-directory: CV-Digital' ở đây vì action này chạy ở root

    - name: Install dependencies # Bước này cần chạy trong thư mục gốc của dự án
      run: npm install --legacy-peer-deps
      working-directory: . # <--- THÊM DÒNG NÀY (hoặc bạn có thể bỏ qua nếu npm install mặc định chạy ở root của repo)

    - name: Build Next.js project # Bước này cần chạy trong thư mục gốc của dự án
      run: npm run build
      working-directory: . # <--- THÊM DÒNG NÀY

    - name: Add .nojekyll file # Bước này cũng cần chạy trong thư mục gốc của dự án
      run: touch ./out/.nojekyll
      working-directory: . # <--- THÊM DÒNG NÀY

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out # Thư mục 'out' sẽ nằm ở gốc dự án sau khi build
        # Không cần 'publish_dir: CV-Digital/out' vì 'out' sẽ được tạo ở gốc repo